export const prompts = [
    { question: "A boundary of mine is", answer: "Being unsupportive of my onion ring obsession" },
    { question: "A daily essential", answer: "Lube (for my Rubik's cube)" },
    { question: "A dream home must include", answer: "You" },
    { question: "A friend's review of me", answer: "To be honest, he's probably made a longer (and better) review about me" },
    { question: "A life goal of mine", answer: "Make the greatest software in the world" },
    { question: "A quick rant about", answer: "" },
    { question: "A random fact I love is", answer: "You can't squat with one hand in the air" },
    { question: "A shower thought I recently had", answer: "If humans had wings, flying would be exercise, and we wouldn't do it" },
    { question: "All I ask is that you", answer: "" },
    { question: "Apparently, my life's soundtrack is", answer: "" },
    { question: "Ask me anything about", answer: "" },
    { question: "Best travel story", answer: "" },
    { question: "Biggest risk I've taken", answer: "Asking my crush to date me with marriage in mind." },
    { question: "Can we talk about", answer: "" },
    { question: "Change my mind about", answer: "Windows and MacOS are just worse" },
    { question: "Choose our first date", answer: "KFC, Nandos or Kebabs (Anime included)" },
    { question: "Cook with me", answer: "" },
    { question: "Dating me is like", answer: "" },
    { question: "Do you agree or disagree that", answer: "" },
    { question: "Don't hate me if I", answer: "Slurp my noodles and moan when I drink the soup" },
    { question: "First round is on me if", answer: "" },
    { question: "Give me travel tips for", answer: "My house to your bed" },
    { question: "Give me your honest opinion about", answer: "" },
    { question: "Green flags I look for", answer: "" },
    { question: "Guess my secret talent", answer: "" },
    { question: "Guess the song", answer: "" },
    { question: "Hi from me and my pet", answer: "" },
    { question: "How to pronounce my name", answer: "" },
    { question: "I bet you can't", answer: "" },
    { question: "I feel most supported when", answer: "" },
    { question: "I geek out on", answer: "" },
    { question: "I get myself out of a funk by", answer: "" },
    { question: "I go crazy for", answer: "" },
    { question: "I hype myself up by", answer: "" },
    { question: "I know the best spot in town for", answer: "" },
    { question: "I recently discovered that", answer: "" },
    { question: "I want someone who", answer: "Cleans my ears whilst I lay my head on their lap" },
    { question: "I wind down by", answer: "" },
    { question: "I wish more people knew", answer: "" },
    { question: "I won't shut up about", answer: "" },
    { question: "I'll brag about you to my friends if", answer: "" },
    { question: "I'll give you the set up, you guess the punchline", answer: "" },
    { question: "I'm convinced that", answer: "" },
    { question: "I'm weirdly attracted to", answer: "" },
    { question: "If loving this is wrong, I don't want to be right", answer: "" },
    { question: "If we won the lottery, let's spend it on", answer: "Food and let's get obese" },
    { question: "Instead of grabbing drinks, let's", answer: "" },
    { question: "I'll fall for you if", answer: "" },
    { question: "I'll pick the topic if you start the conversation", answer: "" },
    { question: "I'm a 10 but", answer: "Together we'll average out to 20" },
    { question: "I'm looking for", answer: "" },
    { question: "Let me teach you how to", answer: "Program in Rust" },
    { question: "Let's debate this topic", answer: "" },
    { question: "Let's break the ice by", answer: "" },
    { question: "Let's chat about", answer: "" },
    { question: "Let's make sure we're on the same page about", answer: "" },
    { question: "Like for tips about", answer: "" },
    { question: "Most spontaneous thing I've done", answer: "" },
    { question: "My BFF's take on why you should date me", answer: "" },
    { question: "My Love Language is", answer: "" },
    { question: "My best Dad Joke", answer: "" },
    { question: "My best celebrity impression", answer: "" },
    { question: "My biggest date fail", answer: "" },
    { question: "My cry-in-the-car song is", answer: "" },
    { question: "My favorite line from a movie", answer: "" },
    { question: "My friends ask me for advice about", answer: "" },
    { question: "My greatest strength", answer: "" },
    { question: "My happy place", answer: "" },
    { question: "My last journal entry was about", answer: "" },
    { question: "My most controversial opinion is", answer: "" },
    { question: "My most irrational fear (is)", answer: "" },
    { question: "My review of", answer: "I'll write an essay for anything you like" },
    { question: "My self-care routine is", answer: "" },
    { question: "My simple pleasures", answer: "" },
    { question: "My therapist would say I", answer: "" },
    { question: "Never have I ever", answer: "" },
    { question: "One thing I'll never do again", answer: "" },
    { question: "Pick our first getaway", answer: "" },
    { question: "Pick the best one", answer: "" },
    { question: "Pick the most underrated", answer: "" },
    { question: "Pick the one that's gotta go", answer: "" },
    { question: "Proof I have musical talent", answer: "" },
    { question: "Put a finger down if", answer: "" },
    { question: "Quick story time", answer: "" },
    { question: "Rate my fit", answer: "" },
    { question: "Saying \"Hi!\" in as many languages I know", answer: "" },
    { question: "Something that's non-negotiable for me is", answer: "" },
    { question: "Something that's special to me", answer: "" },
    { question: "Teach me something about", answer: "" },
    { question: "The best spot in town for pizza is", answer: "" },
    { question: "The best way to ask me out is by", answer: "" },
    { question: "The dorkiest thing about me is", answer: "" },
    { question: "The hallmark of a good relationship is", answer: "" },
    { question: "The key to my heart is", answer: "" },
    { question: "The last time I cried happy tears was", answer: "" },
    { question: "The one thing I've love to know about you is", answer: "" },
    { question: "The one thing you should know about me is", answer: "" },
    { question: "The way to win me over is", answer: "" },
    { question: "Therapy recently taught me", answer: "" },
    { question: "Things I own that just make sense", answer: "" },
    { question: "This year, I really want to", answer: "" },
    { question: "To me, relaxation is", answer: "" },
    { question: "Together, we could", answer: "" },
    { question: "Try to guess this about me", answer: "" },
    { question: "Two truths and a lie", answer: "" },
    { question: "Typical Sunday", answer: "" },
    { question: "Unusual skills", answer: "" },
    { question: "We'll get along if", answer: "" },
    { question: "Weirdest gift I have given or received", answer: "" },
    { question: "We'll instantly hit it off if", answer: "" },
    { question: "We're the same type of weird if", answer: "" },
    { question: "What I order for the table", answer: "" },
    { question: "What if I told you that", answer: "" },
    { question: "When I need advice, I go to", answer: "" },
    { question: "Which do we have in common", answer: "" },
    { question: "Which event should we time travel to?", answer: "" },
    { question: "Which is worth splurging on", answer: "" },
    { question: "Worst idea I've ever had", answer: "" },
    { question: "Would you rather", answer: "" },
    { question: "You should not go out with me if", answer: "" },
    { question: "You should leave a comment if", answer: "" },

];

