#!/usr/bin/env bash


echo "Removing old versions"
rm Johan-Yim.pdf > /dev/null 2>&1


new_file="Johan-Yim.pdf"
echo "Compiling new version"

typst compile cv.typ $new_file

if [[ $? -eq 0 ]]; then 
    echo "Compilation success, written output to $new_file"
else
    echo "Compilation failed"
fi

## OPTIONAL: deploy new cv to website

